- name: Deploy Monitoring Stack
  hosts: monitoring
  become: true
  tasks:

    # Build Prometheus Image
    - name: Build Prometheus Docker image
      docker_image:
        name: prometheus_manual1
        source: build
        build:
          path: ../docker/prometheus

    # Run Prometheus Container
    - name: Run Prometheus container
      docker_container:
        name: prometheus
        image: prometheus_manual1
        network_mode: host
        restart_policy: always
        state: started

    # Build Node Exporter Image
    - name: Build Node Exporter Docker image
      docker_image:
        name: node_exporter_manual
        source: build
        build:
          path: ../docker/node_exporter

    # Run first Node Exporter container on port 9100
    - name: Run Node Exporter container 1
      docker_container:
        name: node_exporter_1
        image: node_exporter_manual
        network_mode: host
        restart_policy: always
        state: started
        command: "/opt/node_exporter/node_exporter --web.listen-address=:9100"

    # Run second Node Exporter container on port 9101
    - name: Run Node Exporter container 2
      docker_container:
        name: node_exporter_2
        image: node_exporter_manual
        network_mode: host
        restart_policy: always
        state: started
        command: "/opt/node_exporter/node_exporter --web.listen-address=:9101"

    # Build Grafana Image
    - name: Build Grafana Docker image
      docker_image:
        name: grafana_manual
        source: build
        build:
          path: ../docker/grafana

    # Run Grafana Container
    - name: Run Grafana container
      docker_container:
        name: grafana
        image: grafana_manual
        network_mode: host
        restart_policy: always
        state: started
